name: build and git tag if not exists
on:
  push:
    branches:
      - main # Default release branch

env:
  TARGET_PROJECT_PATH: src/kr.bbon.Core/
  TARGET_PROJECT_FILE: kr.bbon.Core.csproj
  DOTNET_VERSION: 8.0.x
  
jobs:
  # build job
  build:
    name: "build 👉 ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

  # Git tag job      
  tag:
    name: Create Git tag if not exist.
    needs: [build]
    runs-on: ubuntu-latest
    steps:

      - name: Checkout 
        uses: actions/checkout@v4
      
      - name: Get version 
        uses: bbonkr/get-version-action@v1
        id: get_version
        with:
          project: "${{ env.TARGET_PROJECT_PATH }}${{ env.TARGET_PROJECT_FILE }}"

      - name: Check git tag 
        uses: bbonkr/git-tag-check-action@v1
        id: git_tag_check
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          tag: 'v${{ steps.get_version.outputs.version }}'

      - name: logging
        if: ${{ steps.git_tag_check.outputs.tag != '' }}
        run: |
          echo "Tag ${{ steps.git_tag_check.outputs.tag }} is exists."

      - name: Create git tag
        uses: pkgdeps/git-tag-action@v2
        if: ${{ steps.git_tag_check.outputs.tag == '' }}
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ steps.get_version.outputs.version }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"

  # Reporting
  reporting:
    name: Reporting 
    if: ${{ always() }}
    needs: [build, tag]
    runs-on: ubuntu-latest
    steps:
      - name: Notify to slack
        uses: 8398a7/action-slack@v3
        if: always() # Pick up events even if the job fails or is canceled. 
        with:
          job_name: build
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT:  ${{ toJson(matrix) }}
