name: 'Verify to Build'

on:
  pull_request:

jobs:
  verify-build:
    name: "Verify to build 👉 ${{ matrix.os }} : .NET ${{ matrix.dotnet }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet: ['3.1.x', '5.0.x', '6.0.x']

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal        

  reporting:
    name: 'Reporing'
    needs: [verify-build]
    runs-on: ubuntu-latest
    steps:
      - name: Add comment 
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          OUTPUT: "✅ This pull request is verified to build."
        with:
          msg: ${{ env.OUTPUT }}
          check_for_duplicate_msg: false

      - name: Notify to slack
        uses: 8398a7/action-slack@v3
        if: always() # Pick up events even if the job fails or is canceled. 
        with:
          job_name: verify-build
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT:  ${{ toJson(matrix) }}

      - name: Notify to Microsoft Teams
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}      